stages:
    - build
    - test
    - deploy

cache:
  paths:
  - node_modules/

################
# node latest
################
    
build_node:latest:
    stage: build
    image: node:latest
    script:
        - npm install
        - npm run build
    artifacts:
        name: "qhun-transpiler.$CI_COMMIT_REF_SLUG.$CI_PIPELINE_IID"
        when: on_success
        paths:
            - dist/
            - readme.md
            - package.json
            - LICENSE

test_node:latest:
    stage: test
    image: node:latest
    script:
        - npm install
        - npm run coverage
    coverage: '/\d+\.\d+\%\ \(/'

#########################
# DEPLOY TO GITHUB.COM
#########################
deploy:GitHub:
    stage: deploy
    image: ilyasemenov/gitlab-ci-git-push
    when: on_success
    script:
        - git-push git@github.com:wartoshika/qhun-transpiler.git refs/heads/$CI_COMMIT_REF_NAME
    only:
        - master
        - dev

######################
# DEPLOY TO NPMJS.ORG
######################
deploy:NPM:
    stage: deploy
    image: node:latest
    when: on_success
    dependencies:
      - build_node:latest
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - cat ~/.npmrc
        - npm whoami
        - npm publish
    only:
        - tags
        - triggers