stages:
    - build
    - test
    - deploy

cache:
  paths:
  - node_modules/

################
# node latest
################
    
build_node:latest:
    stage: build
    image: node:latest
    script:
        - npm install
        - npm run build
    artifacts:
        name: "qhun-transpiler.$CI_COMMIT_REF_SLUG.$CI_PIPELINE_IID"
        when: on_success
        paths:
            - dist/
            - readme.md
            - package.json
            - LICENSE

test_node:latest:
    stage: test
    image: node:latest
    script:
        - npm install
        - npm run coverage
    coverage: '/\d+\.\d+\%\ \(/'

#########################
# DEPLOY TO GITHUB.COM
#########################
deploy:GitHub:
    stage: deploy
    when: on_success
    script:
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -H 22 "github.com" >> ~/.ssh/known_hosts
        - git remote add github git@github.com:wartoshika/qhun-transpiler.git || true
        - git push github -u $CI_COMMIT_REF_NAME --follow-tags --force
    only:
        - master
        - dev

######################
# DEPLOY TO NPMJS.ORG
######################
deploy:NPM:
    stage: deploy
    image: node:latest
    when: on_success
    dependencies:
      - build_node:latest
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm publish
    only:
        - tags
        - triggers