stages:
    - build
    - test
    - deploy

cache:
  paths:
  - node_modules/

################
# node 10
################
    
build:node10:
    stage: build
    image: node:10
    script:
        - npm install
        - npm run build
    artifacts:
        name: "qhun-transpiler.$CI_COMMIT_REF_SLUG.$CI_PIPELINE_IID"
        when: on_success
        paths:
            - dist/
            - readme.md
            - package.json
            - LICENSE

test:node10:
    stage: test
    image: node:10
    script:
        - npm install
        - npm run coverage
    coverage: '/\d+\.\d+\%\ \(/'

#########################
# DEPLOY TO GITHUB.COM
#########################
deploy:GitHub:
    stage: deploy
    image: ilyasemenov/gitlab-ci-git-push
    when: on_success
    script:
        - git-push git@github.com:wartoshika/qhun-transpiler.git refs/heads/$CI_COMMIT_REF_NAME
    only:
        - master
        - dev

######################
# DEPLOY TO NPMJS.ORG
######################
deploy:NPM:
    stage: deploy
    image: node:10
    dependencies:
      - build:node10
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_NPMJS_TOKEN}'>.npmrc
        - npm publish
    only:
        - tags

##############################
# DEPLOY TO INTERNAL REGISTRY
##############################
deploy:NPM:
    stage: deploy
    image: node:10
    dependencies:
      - build:node10
    script:
        - echo '//npm-registry.qhun.de/:_authToken=${NPM_INTERNAL_TOKEN}'>.npmrc
        - npm publish --registry http://npm-registry.qhun.de
    only:
        - tags