language: node_js
sudo: false

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

node_js:
- node

install:
  - npm install

script:
  - npm run build
  - npm run test-ci

after_success:
  - npm run coverage:send:coveralls

cache:
  directories:
  - node_modules