language: node_js
sudo: false

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

node_js:
- node

install:
  - npm install

script:
  - npm run test:coverage

after_success:
  - npm run coverage:send:coveralls

before_deploy:
  - npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: dev@qhun.de
  api_key: $NPM_API_KEY
  on:
    tags: true

cache:
  directories:
  - node_modules